name: dich_vu_it
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  file_picker: ^6.0.0
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  intl: ^0.18.1
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  image_picker: ^1.0.4
  animation_list: ^2.2.1
  popover: ^0.2.8+2
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^16.1.0
  syncfusion_flutter_sliders: ^23.1.42
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  cloud_firestore: ^4.12.2
  cached_network_image: ^3.3.0
  firebase_auth: ^4.12.1
  emoji_picker_flutter: ^1.6.3
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  like_button: ^2.0.5
  nb_utils: ^4.4.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/wa_bg.jpg
    - assets/images/
    - assets/images/like.png
    - assets/images/liked.png
    - assets/images/unlike.png
    - assets/images/unliked.png



